services:
  ros1:
    container_name: ros1_noetic_devel
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    pid: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_MASTER_URI=http://simulator:11311/
    ports:
      - "3022:22" # sshd
      - "3080:80" # novnc
      - "3081:3000" # vscode-server
    volumes:
      - ${localWorkspaceFolder}/local_mount:/home/ubuntu/ros_ws
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - ${HOME}/.Xauthority:/home/ubuntu/.Xauthority
    # linux configuration
    # mac_address: 51:91:f3:26:c8:36      # <-- MAC needs to be unique in this network (gerated randomly)
    # networks:
    #   macvlan_ros1:                        # <-- MACVlan Name no need to change, but it needs to be unique
    #     ipv4_address: 192.168.1.111       # <-- Update; must be the IP that you want to use as for the container

# networks:
#   ros_network:
#     driver: macvlan
#     ipv6: false
#     driver_opts:
#       parent: eth0                           # <- Update to match your NIC
#     ipam:
#       config:
#         - subnet: 192.168.1.0/24            # <-- Update
#           gateway: 192.168.1.1              # <-- Update
#           ip_range: 192.168.1.0/24          # <-- Update