# syntax = edrevo/dockerfile-plus

FROM osrf/ros:noetic-desktop-full AS amd64_build_state

INCLUDE+ Dockerfile.root.common

# vscode server
RUN  curl -fOL https://github.com/coder/code-server/releases/download/v4.104.2/code-server_4.104.2_amd64.deb && \
    dpkg -i code-server_4.104.2_amd64.deb && \
    rm code-server_4.104.2_amd64.deb

INCLUDE+ Dockerfile.user.common